### ISSUE TITLE
crashed when run on my MBP

### ISSUE THREAD

**Issue by realcarlos** [kkk669/CoreMLDemos.swiftpm#1]
<img width="1512" alt="截屏2023-09-03 15 36 52" src="https://github.com/kkk669/CoreMLDemos.swiftpm/assets/13853/de23e041-6882-4e1c-8244-8c4e1d7ecb76">

**Comment by kkebo** [comment]
I don't plan to support macOS and Xcode because I'm developing this app on iPad. Please see the "Target platforms" and "Build requirements" on README.md.
