### ISSUE TITLE
Fail to run it on my iPad Air4 (iPadOS 17.1.2)

### ISSUE THREAD

**Issue by zhengyue08** [kkk669/CoreMLDemos.swiftpm#6]
I found this project interesting but failed to run it on my iPad. I followed your "Get Started", and can saw files in swift playground but got this crashed info. Could you tell my how can I fix it? I'm a beginner.
<img width="381" alt="image" src="https://github.com/kkk669/CoreMLDemos.swiftpm/assets/57664875/c1723036-90c6-4d5d-aa08-802379a7511d">

**Comment by kkebo** [comment]
This is a known issue of Swift Playgrounds 4.4.

However, the App Preview should work. Please open README.md or other files other than Swift source files, close the project once, and open it again.

![image](https://github.com/kkk669/CoreMLDemos.swiftpm/assets/601636/8b4cc695-b3ed-4745-a524-dd3cdc4654bc)

**Comment by kkebo** [comment]
This issue occurs not only in this project, but in all my Swift app projects above a certain size. So I think it is an Apple issue. I haven't had a chance to report it to Apple yet, but if you would like to send feedback to Apple, that would be great too.

**Comment by zhengyue08** [comment]
I got the preview, interesting. Thank you for your quick reply.
